if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $
endif

" Specify a directory for plugins
" - For Neovim: ~/.local/share/nvim/plugged
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Any valid git URL is allowed

"""""" Directory management and travel
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" Plug 'sheerun/vim-polyglot'

"""""" Linting and Completion
Plug 'w0rp/ale'

"""""" Vim read .editorconfig file
Plug 'editorconfig/editorconfig-vim'

"""""" Allow multiple cursors on vim
" Plug 'terryma/vim-multiple-cursors'

"""""" Auto insert quotes, parentheses, brackets, braces
Plug 'jiangmiao/auto-pairs'

""" Onedark theme
Plug 'joshdick/onedark.vim'

"""""" Themes
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

"""""" Syntax highlighting js
" Plug 'pangloss/vim-javascript'
" Plug 'mxw/vim-jsx'

"""""" Auto completion
" Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

filetype plugin on
set omnifunc=syntaxcomplete#Complete
set number relativenumber
set numberwidth=2
set breakindent
set autoindent
set smartindent
set expandtab
set softtabstop=2
set tabstop=2
set shiftwidth=2
set ruler
set cursorline
set colorcolumn=80,120
set nowritebackup
set noswapfile
set nobackup
set t_Co=256
syntax on

" let mapleader = ","

" Theme
colorscheme onedark

" Panels navigation
nnoremap <C-H> <C-W><C-H>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>

" Buffers config
""" Buffer navigation
" nnoremap bn :bn
" nnoremap bp :bp

""" Buffer deletion
" nnoremap bd :bd

function! SourceFileIfExists(filename)
  let l:extra_file = fnamemodify(expand($MYVIMRC), ':p:h') . '/' . a:filename
  if filereadable(l:extra_file)
    execute ':so ' . l:extra_file
  endif
endfunc

call SourceFileIfExists('airline.vim')
call SourceFileIfExists('ale.vim')
call SourceFileIfExists('ale-mappings.vim')
call SourceFileIfExists('coc.vim')
call SourceFileIfExists('nerdtree.vim')

" source ~/.config/vim/config/vim-plugins/airline.vim
" source ~/.config/vim/config/vim-plugins/ale.vim
" source ~/.config/vim/config/vim-plugins/ale-mappings.vim
" source ~/.config/vim/config/vim-plugins/nerdtree.vim
" source ~/.config/vim/config/vim-plugins/coc.vim

